include:
  - proxy.yaml

services:
  db:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3


    networks:
      backend:
        ipv4_address: 172.20.0.10
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "5000:8090"
    depends_on:
      - db
      - reverse-proxy
      - ingress-proxy
    networks:
      backend:
        ipv4_address: 172.20.0.5

volumes:
  mysql_data:
